// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/app": {
            "put": {
                "description": "Update app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "Update app",
                "parameters": [
                    {
                        "description": "app",
                        "name": "app",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateAppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Create app",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "Create app",
                "parameters": [
                    {
                        "description": "create app request",
                        "name": "create_app_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateAppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete app",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "Delete app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/app/detail": {
            "get": {
                "description": "Get app detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "Get app detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.App"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/app/list": {
            "get": {
                "description": "Get app list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "Get app list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "kb id",
                        "name": "kb_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.AppListItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/chat/kb": {
            "post": {
                "description": "ChatToKB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "ChatToKB",
                "parameters": [
                    {
                        "description": "ChatToKBReq Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ChatToKBReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/conversation": {
            "get": {
                "description": "get conversation list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversation"
                ],
                "summary": "get conversation list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "app_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "kb_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "per_page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "remote_ip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "subject",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler_v1.ConversationListItems"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/conversation/detail": {
            "get": {
                "description": "get conversation detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversation"
                ],
                "summary": "get conversation detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-SafePoint-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.ConversationDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/doc": {
            "post": {
                "description": "Create Doc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "doc"
                ],
                "summary": "Create Doc",
                "parameters": [
                    {
                        "description": "Doc",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateDocReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/doc/action": {
            "post": {
                "description": "Doc Action",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "doc"
                ],
                "summary": "Doc Action",
                "parameters": [
                    {
                        "description": "Action",
                        "name": "action",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DocActionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/doc/chunk/list": {
            "get": {
                "description": "Get Chunk List",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "doc"
                ],
                "summary": "Get Chunk List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Doc ID",
                        "name": "doc_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.ChunkListItemResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/doc/detail": {
            "get": {
                "description": "Get Doc Detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "doc"
                ],
                "summary": "Get Doc Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Doc ID",
                        "name": "doc_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.DocDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "Update Doc Detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "doc"
                ],
                "summary": "Update Doc Detail",
                "parameters": [
                    {
                        "description": "Doc",
                        "name": "doc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateDocReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/doc/list": {
            "get": {
                "description": "Get Doc List",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "doc"
                ],
                "summary": "Get Doc List",
                "parameters": [
                    {
                        "type": "string",
                        "name": "kb_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.DocListItemResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/doc/parse_url": {
            "post": {
                "description": "Parse URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "doc"
                ],
                "summary": "Parse URL",
                "parameters": [
                    {
                        "description": "Parse URL",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ParseURLReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.ParseURLResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/file/upload": {
            "post": {
                "description": "Upload File",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Upload File",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Knowledge Base ID",
                        "name": "kb_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ObjectUploadResp"
                        }
                    }
                }
            }
        },
        "/api/v1/knowledge_base": {
            "post": {
                "description": "CreateKnowledgeBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge_base"
                ],
                "summary": "CreateKnowledgeBase",
                "parameters": [
                    {
                        "description": "CreateKnowledgeBase Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateKnowledgeBaseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/knowledge_base/detail": {
            "get": {
                "description": "GetKnowledgeBaseDetail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge_base"
                ],
                "summary": "GetKnowledgeBaseDetail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Knowledge Base ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.KnowledgeBaseDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "UpdateKnowledgeBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge_base"
                ],
                "summary": "UpdateKnowledgeBase",
                "parameters": [
                    {
                        "description": "UpdateKnowledgeBase Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateKnowledgeBaseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteKnowledgeBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge_base"
                ],
                "summary": "DeleteKnowledgeBase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Knowledge Base ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/knowledge_base/list": {
            "get": {
                "description": "GetKnowledgeBaseList",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge_base"
                ],
                "summary": "GetKnowledgeBaseList",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.KnowledgeBaseListItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/model": {
            "put": {
                "description": "update model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "parameters": [
                    {
                        "description": "update model request",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateModelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "create model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "summary": "create model",
                "parameters": [
                    {
                        "description": "create model request",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateModelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "model id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/model/activate": {
            "post": {
                "description": "activate model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "summary": "activate model",
                "parameters": [
                    {
                        "description": "activate model request",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ActivateModelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/model/check": {
            "post": {
                "description": "check model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "summary": "check model",
                "parameters": [
                    {
                        "description": "check model request",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CheckModelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.CheckModelResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/model/detail": {
            "get": {
                "description": "get model detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "summary": "get model detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "model id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.ModelDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/model/list": {
            "get": {
                "description": "get model list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "summary": "get model list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.ModelListItem"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/model/provider/supported": {
            "get": {
                "description": "get provider supported model list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "summary": "get provider supported model list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "api_header",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "api_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "base_url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "SiliconFlow",
                            "OpenAI",
                            "Ollama",
                            "DeepSeek",
                            "Moonshot",
                            "AzureOpenAI"
                        ],
                        "type": "string",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.GetProviderModelListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "description": "GetUser",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetUser",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.UserInfoResp"
                        }
                    }
                }
            }
        },
        "/api/v1/user/create": {
            "post": {
                "description": "CreateUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "CreateUser",
                "parameters": [
                    {
                        "description": "CreateUser Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/list": {
            "get": {
                "description": "ListUsers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "ListUsers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.UserListItemResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.LoginResp"
                        }
                    }
                }
            }
        },
        "/api/v1/user/reset_password": {
            "put": {
                "description": "ResetPassword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "ResetPassword",
                "parameters": [
                    {
                        "description": "ResetPassword Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        },
        "/share/v1/app/link": {
            "get": {
                "description": "Get app by link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "Get app by link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "link",
                        "name": "link",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/domain.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.App"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/share/v1/chat/message": {
            "post": {
                "description": "ChatMessage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "ChatMessage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ActivateModelReq": {
            "type": "object",
            "required": [
                "model_id"
            ],
            "properties": {
                "model_id": {
                    "type": "string"
                }
            }
        },
        "domain.App": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kb_id": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "settings": {
                    "$ref": "#/definitions/domain.AppSettings"
                },
                "type": {
                    "$ref": "#/definitions/domain.AppType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.AppListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "settings": {
                    "$ref": "#/definitions/domain.AppSettings"
                },
                "stats": {
                    "$ref": "#/definitions/domain.ConversationStatForApp"
                },
                "type": {
                    "$ref": "#/definitions/domain.AppType"
                }
            }
        },
        "domain.AppSettings": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "dingbot_aes_key": {
                    "type": "string"
                },
                "dingbot_client_id": {
                    "description": "dingbot",
                    "type": "string"
                },
                "dingbot_token": {
                    "type": "string"
                },
                "dingbot_welcome_str": {
                    "type": "string"
                },
                "feishubot_app_id": {
                    "description": "feishu",
                    "type": "string"
                },
                "feishubot_app_secret": {
                    "type": "string"
                },
                "feishubot_encrypt_key": {
                    "type": "string"
                },
                "feishubot_verification_token": {
                    "type": "string"
                },
                "feishubot_welcome_str": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "recommend_doc_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommend_questions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "search_placeholder": {
                    "type": "string"
                },
                "wecombot_agent_id": {
                    "description": "Wecom",
                    "type": "integer"
                },
                "wecombot_corp_id": {
                    "type": "string"
                },
                "wecombot_corp_secret": {
                    "type": "string"
                },
                "wecombot_suite_encoding_aes_key": {
                    "type": "string"
                },
                "wecombot_suite_id": {
                    "type": "string"
                },
                "wecombot_suite_token": {
                    "type": "string"
                },
                "wecombot_welcome_str": {
                    "type": "string"
                },
                "welcome_str": {
                    "type": "string"
                }
            }
        },
        "domain.AppType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "AppTypeWeb",
                "AppTypeWidget",
                "AppTypeDingbot",
                "AppTypeFeishu",
                "AppTypeWecom"
            ]
        },
        "domain.ChatRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "conversation_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                }
            }
        },
        "domain.ChatToKBMessage": {
            "type": "object",
            "required": [
                "content",
                "role"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "domain.ChatToKBReq": {
            "type": "object",
            "required": [
                "kb_id",
                "messages"
            ],
            "properties": {
                "kb_id": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ChatToKBMessage"
                    }
                }
            }
        },
        "domain.CheckModelReq": {
            "type": "object",
            "required": [
                "base_url",
                "model",
                "provider"
            ],
            "properties": {
                "api_header": {
                    "type": "string"
                },
                "api_key": {
                    "type": "string"
                },
                "api_version": {
                    "description": "for azure openai",
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "enum": [
                        "OpenAI",
                        "Ollama",
                        "DeepSeek",
                        "SiliconFlow",
                        "Moonshot",
                        "Other",
                        "AzureOpenAI"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.ModelProvider"
                        }
                    ]
                }
            }
        },
        "domain.CheckModelResp": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "domain.ChunkListItemResp": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.ConversationCount": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "domain.ConversationDetailResp": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConversationMessage"
                    }
                },
                "references": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConversationReference"
                    }
                },
                "remote_ip": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "domain.ConversationListItem": {
            "type": "object",
            "properties": {
                "app_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "remote_ip": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "domain.ConversationMessage": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "completion_tokens": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "conversation_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "provider": {
                    "description": "model",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.ModelProvider"
                        }
                    ]
                },
                "remote_ip": {
                    "description": "stats",
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/schema.RoleType"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "domain.ConversationReference": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "conversation_id": {
                    "type": "string"
                },
                "doc_id": {
                    "type": "string"
                },
                "favicon": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.ConversationStatForApp": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "day_counts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConversationCount"
                    }
                },
                "last_24h_count": {
                    "type": "integer"
                },
                "last_24h_ip_count": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateAppReq": {
            "type": "object",
            "required": [
                "kb_id",
                "type"
            ],
            "properties": {
                "icon": {
                    "type": "string"
                },
                "kb_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.AppType"
                        }
                    ]
                }
            }
        },
        "domain.CreateDocReq": {
            "type": "object",
            "required": [
                "kb_id",
                "source"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "file_key": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "kb_id": {
                    "type": "string"
                },
                "source": {
                    "enum": [
                        1,
                        2,
                        3
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.DocSource"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.CreateKnowledgeBaseReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.CreateModelReq": {
            "type": "object",
            "required": [
                "base_url",
                "model",
                "provider"
            ],
            "properties": {
                "api_header": {
                    "type": "string"
                },
                "api_key": {
                    "type": "string"
                },
                "api_version": {
                    "description": "for azure openai",
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "enum": [
                        "OpenAI",
                        "Ollama",
                        "DeepSeek",
                        "SiliconFlow",
                        "Moonshot",
                        "Other",
                        "AzureOpenAI"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.ModelProvider"
                        }
                    ]
                }
            }
        },
        "domain.CreateUserReq": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "domain.DocActionReq": {
            "type": "object",
            "required": [
                "action",
                "doc_ids"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "delete"
                    ]
                },
                "doc_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.DocDetailResp": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/domain.DocMeta"
                },
                "resource_type": {
                    "$ref": "#/definitions/domain.ResourceType"
                },
                "source": {
                    "$ref": "#/definitions/domain.DocSource"
                },
                "status": {
                    "$ref": "#/definitions/domain.DocStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.DocListItemResp": {
            "type": "object",
            "properties": {
                "chunk_count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "favicon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "resource_type": {
                    "$ref": "#/definitions/domain.ResourceType"
                },
                "source": {
                    "$ref": "#/definitions/domain.DocSource"
                },
                "status": {
                    "$ref": "#/definitions/domain.DocStatus"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "word_count": {
                    "type": "integer"
                }
            }
        },
        "domain.DocMeta": {
            "type": "object",
            "properties": {
                "charset": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "doc_type": {
                    "$ref": "#/definitions/domain.ResourceType"
                },
                "favicon": {
                    "type": "string"
                },
                "keywords": {
                    "type": "string"
                },
                "screenshot": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.DocSource": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "DocSourceURL",
                "DocSourceFile",
                "DocSourceManual"
            ]
        },
        "domain.DocStatus": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "DocStatusPending",
                "DocStatusPublished",
                "DocStatusFailed"
            ]
        },
        "domain.GetProviderModelListResp": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProviderModelListItem"
                    }
                }
            }
        },
        "domain.KBStats": {
            "type": "object",
            "properties": {
                "chunk_count": {
                    "type": "integer"
                },
                "doc_count": {
                    "type": "integer"
                },
                "kb_id": {
                    "type": "string"
                },
                "word_count": {
                    "type": "integer"
                }
            }
        },
        "domain.KnowledgeBaseDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.KnowledgeBaseListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/domain.KBStats"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.LoginReq": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.LoginResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "domain.ModelDetailResp": {
            "type": "object",
            "properties": {
                "api_header": {
                    "type": "string"
                },
                "api_key": {
                    "type": "string"
                },
                "api_version": {
                    "description": "for azure openai",
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "completion_tokens": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "model": {
                    "type": "string"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "provider": {
                    "$ref": "#/definitions/domain.ModelProvider"
                },
                "total_tokens": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.ModelListItem": {
            "type": "object",
            "properties": {
                "api_header": {
                    "type": "string"
                },
                "api_key": {
                    "type": "string"
                },
                "api_version": {
                    "description": "for azure openai",
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "completion_tokens": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "model": {
                    "type": "string"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "provider": {
                    "$ref": "#/definitions/domain.ModelProvider"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "domain.ModelProvider": {
            "type": "string",
            "enum": [
                "OpenAI",
                "Ollama",
                "DeepSeek",
                "Moonshot",
                "SiliconFlow",
                "AzureOpenAI",
                "Other"
            ],
            "x-enum-varnames": [
                "ModelProviderBrandOpenAI",
                "ModelProviderBrandOllama",
                "ModelProviderBrandDeepSeek",
                "ModelProviderBrandMoonshot",
                "ModelProviderBrandSiliconFlow",
                "ModelProviderBrandAzureOpenAI",
                "ModelProviderBrandOther"
            ]
        },
        "domain.ObjectUploadResp": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "domain.ParseURLItem": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "published": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.ParseURLReq": {
            "type": "object",
            "required": [
                "type",
                "url"
            ],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "RSS",
                        "Sitemap"
                    ]
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.ParseURLResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ParseURLItem"
                    }
                }
            }
        },
        "domain.ProviderModelListItem": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                }
            }
        },
        "domain.ResetPasswordReq": {
            "type": "object",
            "required": [
                "id",
                "new_password"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "domain.ResourceType": {
            "type": "string",
            "enum": [
                "WebPage",
                "PlainText",
                "Excel",
                "Word",
                "PDF",
                "Unknown"
            ],
            "x-enum-varnames": [
                "ResourceTypeWebPage",
                "ResourceTypePlainText",
                "ResourceTypeExcel",
                "ResourceTypeWord",
                "ResourceTypePDF",
                "ResourceTypeUnknown"
            ]
        },
        "domain.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.UpdateAppReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "settings": {
                    "$ref": "#/definitions/domain.AppSettings"
                }
            }
        },
        "domain.UpdateDocReq": {
            "type": "object",
            "required": [
                "doc_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "doc_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateKnowledgeBaseReq": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateModelReq": {
            "type": "object",
            "required": [
                "base_url",
                "id",
                "model"
            ],
            "properties": {
                "api_header": {
                    "type": "string"
                },
                "api_key": {
                    "type": "string"
                },
                "api_version": {
                    "description": "for azure openai",
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "domain.UserInfoResp": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_access": {
                    "type": "string"
                }
            }
        },
        "domain.UserListItemResp": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_access": {
                    "type": "string"
                }
            }
        },
        "handler_v1.ConversationListItems": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConversationListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "schema.RoleType": {
            "type": "string",
            "enum": [
                "assistant",
                "user",
                "system",
                "tool"
            ],
            "x-enum-varnames": [
                "Assistant",
                "User",
                "System",
                "Tool"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
