export const CountryEnums = {
  "Afghanistan": "af",
  "Aland Islands": "ax",
  "Albania": "al",
  "Algeria": "dz",
  "American Samoa": "as",
  "Andorra": "ad",
  "Angola": "ao",
  "Anguilla": "ai",
  "Antarctica": "aq",
  "Antigua and Barbuda": "ag",
  "Argentina": "ar",
  "Armenia": "am",
  "Aruba": "aw",
  "Ascension Island": "sh-ac",
  "Association of Southeast Asian Nations": "asean",
  "Australia": "au",
  "Austria": "at",
  "Azerbaijan": "az",
  "Bahamas": "bs",
  "Bahrain": "bh",
  "Bangladesh": "bd",
  "Barbados": "bb",
  "Basque Country": "es-pv",
  "Belarus": "by",
  "Belgium": "be",
  "Belize": "bz",
  "Benin": "bj",
  "Bermuda": "bm",
  "Bhutan": "bt",
  "Bolivia": "bo",
  "Bonaire, Sint Eustatius and Saba": "bq",
  "Bosnia and Herzegovina": "ba",
  "Botswana": "bw",
  "Bouvet Island": "bv",
  "Brazil": "br",
  "British Indian Ocean Territory": "io",
  "Brunei Darussalam": "bn",
  "Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cabo Verde": "cv",
  "Cambodia": "kh",
  "Cameroon": "cm",
  "Canada": "ca",
  "Canary Islands": "ic",
  "Catalonia": "es-ct",
  "Cayman Islands": "ky",
  "Central African Republic": "cf",
  "Central European Free Trade Agreement": "cefta",
  "Chad": "td",
  "Chile": "cl",
  "China": "cn",
  "Christmas Island": "cx",
  "Clipperton Island": "cp",
  "Cocos (Keeling) Islands": "cc",
  "Colombia": "co",
  "Comoros": "km",
  "Cook Islands": "ck",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Cuba": "cu",
  "Curaçao": "cw",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Côte d'Ivoire": "ci",
  "Democratic Republic of the Congo": "cd",
  "Denmark": "dk",
  "Diego Garcia": "dg",
  "Djibouti": "dj",
  "Dominica": "dm",
  "Dominican Republic": "do",
  "East African Community": "eac",
  "Ecuador": "ec",
  "Egypt": "eg",
  "El Salvador": "sv",
  "England": "gb-eng",
  "Equatorial Guinea": "gq",
  "Eritrea": "er",
  "Estonia": "ee",
  "Eswatini": "sz",
  "Ethiopia": "et",
  "Europe": "eu",
  "Falkland Islands": "fk",
  "Faroe Islands": "fo",
  "Federated States of Micronesia": "fm",
  "Fiji": "fj",
  "Finland": "fi",
  "France": "fr",
  "French Guiana": "gf",
  "French Polynesia": "pf",
  "French Southern Territories": "tf",
  "Gabon": "ga",
  "Galicia": "es-ga",
  "Gambia": "gm",
  "Georgia": "ge",
  "Germany": "de",
  "Ghana": "gh",
  "Gibraltar": "gi",
  "Greece": "gr",
  "Greenland": "gl",
  "Grenada": "gd",
  "Guadeloupe": "gp",
  "Guam": "gu",
  "Guatemala": "gt",
  "Guernsey": "gg",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Guyana": "gy",
  "Haiti": "ht",
  "Heard Island and McDonald Islands": "hm",
  "Holy See": "va",
  "Honduras": "hn",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "Iceland": "is",
  "India": "in",
  "Indonesia": "id",
  "Iran": "ir",
  "Iraq": "iq",
  "Ireland": "ie",
  "Isle of Man": "im",
  "Israel": "il",
  "Italy": "it",
  "Jamaica": "jm",
  "Japan": "jp",
  "Jersey": "je",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kiribati": "ki",
  "Kosovo": "xk",
  "Kuwait": "kw",
  "Kyrgyzstan": "kg",
  "Laos": "la",
  "Latvia": "lv",
  "League of Arab States": "arab",
  "Lebanon": "lb",
  "Lesotho": "ls",
  "Liberia": "lr",
  "Libya": "ly",
  "Liechtenstein": "li",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Macau": "mo",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Malaysia": "my",
  "Maldives": "mv",
  "Mali": "ml",
  "Malta": "mt",
  "Marshall Islands": "mh",
  "Martinique": "mq",
  "Mauritania": "mr",
  "Mauritius": "mu",
  "Mayotte": "yt",
  "Mexico": "mx",
  "Moldova": "md",
  "Monaco": "mc",
  "Mongolia": "mn",
  "Montenegro": "me",
  "Montserrat": "ms",
  "Morocco": "ma",
  "Mozambique": "mz",
  "Myanmar": "mm",
  "Namibia": "na",
  "Nauru": "nr",
  "Nepal": "np",
  "The Netherlands": "nl",
  "New Caledonia": "nc",
  "New Zealand": "nz",
  "Nicaragua": "ni",
  "Niger": "ne",
  "Nigeria": "ng",
  "Niue": "nu",
  "Norfolk Island": "nf",
  "North Korea": "kp",
  "North Macedonia": "mk",
  "Northern Ireland": "gb-nir",
  "Northern Mariana Islands": "mp",
  "Norway": "no",
  "Oman": "om",
  "Pacific Community": "pc",
  "Pakistan": "pk",
  "Palau": "pw",
  "Panama": "pa",
  "Papua New Guinea": "pg",
  "Paraguay": "py",
  "Peru": "pe",
  "Philippines": "ph",
  "Pitcairn": "pn",
  "Poland": "pl",
  "Portugal": "pt",
  "Puerto Rico": "pr",
  "Qatar": "qa",
  "Republic of the Congo": "cg",
  "Romania": "ro",
  "Russia": "ru",
  "Rwanda": "rw",
  "Réunion": "re",
  "Saint Barthélemy": "bl",
  "Saint Helena": "sh-hl",
  "Saint Helena, Ascension and Tristan da Cunha": "sh",
  "Saint Kitts and Nevis": "kn",
  "Saint Lucia": "lc",
  "Saint Martin": "mf",
  "Saint Pierre and Miquelon": "pm",
  "Saint Vincent and the Grenadines": "vc",
  "Samoa": "ws",
  "San Marino": "sm",
  "Sao Tome and Principe": "st",
  "Saudi Arabia": "sa",
  "Scotland": "gb-sct",
  "Senegal": "sn",
  "Serbia": "rs",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Singapore": "sg",
  "Sint Maarten": "sx",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Solomon Islands": "sb",
  "Somalia": "so",
  "South Africa": "za",
  "South Georgia and the South Sandwich Islands": "gs",
  "South Korea": "kr",
  "South Sudan": "ss",
  "Spain": "es",
  "Sri Lanka": "lk",
  "State of Palestine": "ps",
  "Sudan": "sd",
  "Suriname": "sr",
  "Svalbard and Jan Mayen": "sj",
  "Sweden": "se",
  "Switzerland": "ch",
  "Syria": "sy",
  "Taiwan": "tw",
  "Tajikistan": "tj",
  "Tanzania": "tz",
  "Thailand": "th",
  "Timor-Leste": "tl",
  "Togo": "tg",
  "Tokelau": "tk",
  "Tonga": "to",
  "Trinidad and Tobago": "tt",
  "Tristan da Cunha": "sh-ta",
  "Tunisia": "tn",
  "Turkmenistan": "tm",
  "Turks and Caicos Islands": "tc",
  "Tuvalu": "tv",
  "Türkiye": "tr",
  "Uganda": "ug",
  "Ukraine": "ua",
  "United Arab Emirates": "ae",
  "United Kingdom": "gb",
  "United Nations": "un",
  "United States": "us",
  "Unknown": "xx",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Vanuatu": "vu",
  "Venezuela": "ve",
  "Vietnam": "vn",
  "Viet Nam": "vn",
  "Virgin Islands (British)": "vg",
  "Virgin Islands (U.S.)": "vi",
  "Wales": "gb-wls",
  "Wallis and Futuna": "wf",
  "Western Sahara": "eh",
  "Yemen": "ye",
  "Zambia": "zm",
  "Zimbabwe": "zw",
  "保留地址": "xx",
  '不丹': "bt",
  '东帝汶': "tl",
  '中国': "cn",
  '中非共和国': "cf",
  '丹麦': "dk",
  '乌克兰': "ua",
  '乌兹别克斯坦': "uz",
  '乌干达': "ug",
  '乌拉圭': "uy",
  '乍得': "td",
  '也门': "ye",
  '亚美尼亚': "am",
  '以色列': "il",
  '伊拉克': "iq",
  '伊朗': "ir",
  '伯利兹': "bz",
  '佛得角': "cv",
  '俄罗斯': "ru",
  '保加利亚': "bg",
  '克罗地亚': "hr",
  '关岛(美国)': "gu",
  '冈比亚': "gm",
  '冰岛': "is",
  '几内亚': "gn",
  '几内亚比绍': "gw",
  '列支敦士登': "li",
  '刚果(金)': "cd",
  '刚果共和国': "cg",
  '利比亚': "ly",
  '利比里亚': "lr",
  '加拿大': "ca",
  '加纳': "gh",
  '加蓬': "ga",
  '匈牙利': "hu",
  '北朝鲜': "kp",
  '北马里亚纳群岛(美国)': "mp",
  '南苏丹': "ss",
  '南非': "za",
  '博茨瓦纳': "bw",
  '卡塔尔': "qa",
  '卢旺达': "rw",
  '卢森堡': "lu",
  '印度': "in",
  '印度尼西亚': "id",
  '危地马拉': "gt",
  '厄瓜多尔': "ec",
  '厄立特里亚': "er",
  '叙利亚': "sy",
  '古巴': "cu",
  '台湾(中国)': "tw",
  '吉尔吉斯斯坦': "kg",
  '吉布提': "dj",
  '哈萨克斯坦': "kz",
  '哥伦比亚': "co",
  '哥斯达黎加': "cr",
  '喀麦隆': "cm",
  '国家': "简称",
  '图瓦卢': "tv",
  '土库曼斯坦': "tm",
  '土耳其': "tr",
  '圣卢西亚': "lc",
  '圣基茨和尼维斯': "kn",
  '圣多美和普林西比': "st",
  '圣文森特和格林纳丁斯': "vc",
  '圣皮埃尔和密克隆岛(法国)': "pm",
  '圣赫勒拿': "sh",
  '圣马力诺': "sm",
  '圭亚那': "gy",
  '坦桑尼亚': "tz",
  '埃及': "eg",
  '埃塞俄比亚': "et",
  '基里巴斯': "ki",
  '塔吉克斯坦': "tj",
  '塞内加尔': "sn",
  '塞尔维亚共和国': "rs",
  '塞拉利昂': "sl",
  '塞浦路斯': "cy",
  '塞舌尔': "sc",
  '墨西哥': "mx",
  '多哥': "tg",
  '多米尼克': "dm",
  '多米尼加共和国': "do",
  '奥地利': "at",
  '委内瑞拉': "ve",
  '孟加拉国': "bd",
  '安哥拉': "ao",
  '安圭拉': "ai",
  '安提瓜和巴布达': "ag",
  '安道尔': "ad",
  '密克罗尼西亚联邦': "fm",
  '尼加拉瓜': "ni",
  '尼日利亚': "ng",
  '尼日尔': "ne",
  '尼泊尔': "np",
  '巴勒斯坦': "ps",
  '巴哈马': "bs",
  '巴基斯坦': "pk",
  '巴巴多斯': "bb",
  '巴布亚新几内亚': "pg",
  '巴拉圭': "py",
  '巴拿马': "pa",
  '巴林': "bh",
  '巴西': "br",
  '布基纳法索': "bf",
  '布隆迪': "bi",
  '希腊': "gr",
  '帕劳': "pw",
  '库克群岛(新西兰)': "ck",
  '开曼群岛(英国)': "ky",
  '德国': "de",
  '意大利': "it",
  '所罗门群岛': "sb",
  '托克劳': "tk",
  '拉脱维亚': "lv",
  '挪威': "no",
  '捷克': "cz",
  '摩尔多瓦': "md",
  '摩洛哥': "ma",
  '摩纳哥': "mc",
  '文莱': "bn",
  '斐济': "fj",
  '斯威士兰': "sz",
  '斯洛伐克': "sk",
  '斯洛文尼亚': "si",
  '斯里兰卡': "lk",
  '新加坡': "sg",
  '新喀里多尼亚(法国)': "nc",
  '新西兰': "nz",
  '日本': "jp",
  '智利': "cl",
  '柬埔寨': "kh",
  '格林纳达': "gd",
  '格陵兰': "gl",
  '格鲁吉亚': "ge",
  '比利时': "be",
  '毛里塔尼亚': "mr",
  '毛里求斯': "mu",
  '汤加': "to",
  '沙特阿拉伯': "sa",
  '没有找到相关国家': "",
  '法国': "fr",
  '法属圭亚那(法国)': "gf",
  '法属玻利尼西亚': "pf",
  '法罗群岛(丹麦)': "fo",
  '波兰': "pl",
  '波多黎各(美国)': "pr",
  '波黑': "ba",
  '泰国': "th",
  '津巴布韦': "zw",
  '洪都拉斯': "hn",
  '海地': "ht",
  '澳大利亚': "au",
  '澳门(中国)': "mo",
  '爱尔兰共和国': "ie",
  '爱沙尼亚': "ee",
  '牙买加': "jm",
  '特克斯和凯科斯群岛(英国)': "tc",
  '特立尼达和多巴哥': "tt",
  '玻利维亚': "bo",
  '瑙鲁': "nr",
  '瑞典': "se",
  '瑞士': "ch",
  '瓜德罗普': "gp",
  '瓦利斯和富图纳群岛(法国)': "wf",
  '瓦努阿图': "vu",
  '留尼汪(法国)': "re",
  '白俄罗斯': "by",
  '百慕大': "bm",
  '直布罗陀(英国)': "gi",
  '科威特': "kw",
  '科摩罗': "km",
  '科特迪瓦': "ci",
  '秘鲁': "pe",
  '突尼斯': "tn",
  '立陶宛': "lt",
  '索马里': "so",
  '约旦': "jo",
  '纳米比亚': "na",
  '纽埃': "nu",
  '缅甸': "mm",
  '罗马尼亚': "ro",
  '美国': "us",
  '美属萨摩亚(美国)': "as",
  '老挝': "la",
  '肯尼亚': "ke",
  '芬兰': "fi",
  '苏丹': "sd",
  '苏里南': "sr",
  '英国': "gb",
  '英属维京群岛(英国)': "vg",
  '荷兰': "nl",
  '荷属安的列斯': "",
  '莫桑比克': "mz",
  '莱索托': "ls",
  '菲律宾': "ph",
  '萨尔瓦多': "sv",
  '萨摩亚': "ws",
  '葡萄牙': "pt",
  '蒙古国': "mn",
  '蒙塞拉特岛(英国)': "ms",
  '西班牙': "es",
  '贝宁': "bj",
  '赞比亚': "zm",
  '赤道几内亚': "gq",
  '越南': "vn",
  '阿塞拜疆': "az",
  '阿富汗': "af",
  '阿尔及利亚': "dz",
  '阿尔巴尼亚': "al",
  '阿拉伯联合酋长国': "ae",
  '阿曼': "om",
  '阿根廷': "ar",
  '阿鲁巴': "aw",
  '韩国': "kr",
  '香港(中国)': "hk",
  '马其顿': "mk",
  '马尔代夫': "mv",
  '马拉维': "mw",
  '马提尼克(法国)': "mq",
  '马来西亚': "my",
  '马约特': "yt",
  '马绍尔群岛': "mh",
  '马耳他': "mt",
  '马达加斯加': "mg",
  '马里共和国': "ml",
  '黎巴嫩': "lb",
  '黑山共和国': "me",
}